### PR TITLE
Build data-sets using docker

### PR DESCRIPTION
**Pull request by yonidavidson**
1.Add pyc and data files to .gitignore
2. Build database using docker

### CODE REVIEW

**Comment by yonidavidson** [comment]
@osh : Hi, Are you reviewing my pr ?

**Comment by l11x0m7** [comment]
@yonidavidson Have you ever used this package? I wonder which mapper should I use in `transmitters.py` files.

**Comment by osh** [comment]
@l11x0m7 https://github.com/gr-vt/gr-mapper

**Comment by l11x0m7** [comment]
@osh thanks

**Pull request merged**
